import { ExecutiveProgram } from "@/types/program";

export const PROGRAMS_DATA: ExecutiveProgram[] = [
  {
    id: "gen-ai-enterprise",
    title: "Generative AI & LLM Engineering for Enterprise",
    category: "Generative AI",
    description: "Master modern AI architecture, RAG systems, fine-tuning open-source models, and operationalizing generative AI for enterprise workflows.",
    duration: "8-12 Weeks",
    format: "Live Online",
    targetAudience: "Engineering Managers, Tech Leads, AI & Software Engineers",
    keyOutcomes: [
      "Deploy production RAG architectures",
      "LLM fine-tuning & prompt engineering",
      "Enterprise AI safety & governance framework",
    ],
    featuredBadge: "High Demand",
    accentColor: "from-blue-600 to-indigo-600",
  },
  {
    id: "tech-data-leadership",
    title: "Executive Data Science & Big Data Analytics",
    category: "Tech & Data",
    description: "Transform raw organization data into strategic business leverage with advanced predictive analytics, ML pipelines, and data governance.",
    duration: "10 Weeks",
    format: "Hybrid Cohort",
    targetAudience: "Data Analysts, Product Managers, BI Directors",
    keyOutcomes: [
      "End-to-end Machine Learning pipelines",
      "Executive data visualization & storytelling",
      "Cloud data infrastructure strategy",
    ],
    featuredBadge: "Co-Created",
    accentColor: "from-cyan-600 to-blue-600",
  },
  {
    id: "strategic-leadership",
    title: "Strategic Digital Transformation & Leadership",
    category: "Leadership Development",
    description: "Equip senior leaders with the mindset, tools, and change management strategies to lead digital-first enterprise organizations.",
    duration: "6 Weeks",
    format: "In-Person",
    targetAudience: "VPs, Directors, CXOs, L&D Heads",
    keyOutcomes: [
      "Digital business model innovation",
      "Agile transformation frameworks",
      "Cross-functional strategic execution",
    ],
    featuredBadge: "Executive Level",
    accentColor: "from-indigo-600 to-purple-600",
  },
  {
    id: "product-innovation",
    title: "AI-Powered Enterprise Product Management",
    category: "Product Innovation",
    description: "Build, launch, and scale market-leading products integrating AI capabilities, user-centric discovery, and data-backed roadmaps.",
    duration: "8 Weeks",
    format: "Live Online",
    targetAudience: "Product Managers, Growth Leads, Strategy Managers",
    keyOutcomes: [
      "AI product lifecycle strategy",
      "User research & rapid prototyping",
      "Product metrics & growth loops",
    ],
    accentColor: "from-emerald-600 to-teal-600",
  },
  {
    id: "operations-excellence",
    title: "Operational Excellence & Agile Logistics",
    category: "Operations Management",
    description: "Streamline cross-enterprise supply chains, automate routine workflows, and foster continuous process optimization across departments.",
    duration: "6 Weeks",
    format: "Live Online",
    targetAudience: "Operations Directors, Supply Chain Leads, Process Owners",
    keyOutcomes: [
      "Lean & Agile operations framework",
      "RPA & process automation strategy",
      "Cost-efficiency & KPI tracking",
    ],
    accentColor: "from-amber-600 to-orange-600",
  },
  {
    id: "fintech-innovation",
    title: "Fintech, Blockchain & Enterprise Payments",
    category: "Fintech",
    description: "Navigate global financial technology disruptions, open banking APIs, compliance technology, and digital ledger architectures.",
    duration: "8 Weeks",
    format: "Hybrid Cohort",
    targetAudience: "Finance Managers, Banking Innovation Teams, Risk Officers",
    keyOutcomes: [
      "Open API & Embedded Finance models",
      "RegTech compliance & security",
      "Digital payment infrastructure strategy",
    ],
    accentColor: "from-violet-600 to-blue-600",
  },
];
